airlines/urls.py
from django.urls import path

from .views import *

app_name = "airlines"

urlpatterns = [
    path("", AirlineListView.as_view(), name="airline_list"),
    path("create", AirlineCreateView.as_view(), name="airline_create"),
    path("<int:pk>/edit", AirlineUpdateView.as_view(), name="airline_update"),
    path("<int:pk>/delete", AirlineDeleteView.as_view(), name="airline_delete"),
]

airports/urls.py
from django.urls import path

from .views import *

app_name = "airports"

urlpatterns = [
    path("", AirportListView.as_view(), name="airport_list"),
    path("create", AirportCreateView.as_view(), name="airport_create"),
    path("<int:pk>/edit", AirportUpdateView.as_view(), name="airport_update"),
    path("<int:pk>/delete", AirportDeleteView.as_view(), name="airport_delete"),
]

bookings/urls.py
from django.urls import path

from .views import *

app_name = "bookings"

urlpatterns = [
    path("", BookingListView.as_view(), name="booking_list"),
    path("create", BookingCreateView.as_view(), name="booking_create"),
    path("<int:pk>/cancel", BookingCancelView.as_view(), name="booking_cancel"),
    path("<int:pk>/detail", BookingDetailView.as_view(), name="booking_detail"),
]

flight_booking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include
from django.urls import path


def redirect_to_login(request):
    if request.user.is_authenticated:
        return redirect("dashboard:home")  # Adjust this to the name of your home view
    else:
        return redirect("users:login")  # Adjust this to the name of your login view


urlpatterns = [
    path("", redirect_to_login, name="redirect_to_login"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("flights/", include("flights.urls")),
    path("airlines/", include("airlines.urls")),
    path("airports/", include("airports.urls")),
    path("bookings/", include("bookings.urls")),
]


# TODO: the static endpoint handling should be removed from here in production environment
# and needs to use nginx or apache configurations for the same.
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flights/urls.py
from django.urls import path

from .views import FlightCreateView
from .views import FlightDeleteView
from .views import FlightDetailView
from .views import FlightListView
from .views import FlightScheduleCreateView
from .views import FlightScheduleListView
from .views import FlightUpdateView

app_name = "flights"

urlpatterns = [
    path("", FlightListView.as_view(), name="flight_list"),
    path("create/", FlightCreateView.as_view(), name="flight_create"),
    path("<int:pk>/edit/", FlightUpdateView.as_view(), name="flight_update"),
    path("<int:pk>/delete/", FlightDeleteView.as_view(), name="flight_delete"),
    path("<int:pk>/detail/", FlightDetailView.as_view(), name="flight_detail"),
    path("schedule/", FlightScheduleListView.as_view(), name="flight_schedule_list"),
    path(
        "schedule/create/",
        FlightScheduleCreateView.as_view(),
        name="flight_schedule_create",
    ),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import CustomLoginView
from .views import ProfileEditView
from .views import UserCreateView
from .views import UserDeleteView
from .views import UserListView

app_name = "users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="users:login"), name="logout"),
    path("profile/edit/", ProfileEditView.as_view(), name="profile_edit"),
    path("admin/users/", UserListView.as_view(), name="user_list"),
    path("admin/users/create/", UserCreateView.as_view(), name="user_create"),
    path("admin/users/<int:pk>/edit/", ProfileEditView.as_view(), name="user_update"),
    path("admin/users/<int:pk>/delete/", UserDeleteView.as_view(), name="user_delete"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Dashboard{% endblock %}</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <div class="wrapper">
        <nav class="sidebar">
            <div class="logo">
                <a href="{% url 'dashboard:home' %}">
                    <img src="{% static 'images/logo.png' %}" alt="Logo">
                </a>
            </div>
            <a href="{% url 'dashboard:home' %}">Home</a>
            <a href="{% url 'flights:flight_list' %}">Flights</a>
            <a href="{% url 'airlines:airline_list' %}">Airlines</a>
            <a href="{% url 'airports:airport_list' %}">Airports</a>
            {% if request.user.role == "admin" %}
                <a href="{% url 'users:user_list' %}">Users</a>
            {% endif %}
            <a href="{% url 'bookings:booking_list' %}">Bookings</a>
            <div class="bottom-links">
                <a href="#">Settings</a>
                <form id="logout-form" action="{% url 'users:logout' %}" method="POST" style="display: none;">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
                <a href="#" class="nav-link" onclick="document.getElementById('logout-form').submit();">Logout</a>
            </div>
        </nav>
        <div class="content">
            <div class="profile">
                <div class="profile_inner">
                    {% if request.user.profile.profile_picture %}
                        <img src="{{ request.user.profile.profile_picture.url }}" alt="Profile Picture">
                    {% else %}
                        <img src="{% static 'images/img.png' %}" alt="Default Image">
                    {% endif %}
                    <p>
                        <a href="{% url 'users:profile_edit' %}">{{ request.user.full_name }}</a>
                    </p>
                </div>
            </div>
            <hr/>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>